"""Shared fixtures for the system test suite.

This file is the single source of truth for surface discovery and health
gating. Everything under tests/system/ imports from here.

FAIL LOUD, NOT SILENT: when STAYCURRENT_REQUIRE_SERVICES=1 (set by CI), an
unreachable surface is a FAILURE. Locally (flag unset) the same condition
skips, so the inner loop stays ergonomic.
"""

import os
import shlex
import subprocess

import httpx
import pytest
from tenacity import RetryError, retry, stop_after_delay, wait_exponential

REQUIRE_SERVICES = os.environ.get("STAYCURRENT_REQUIRE_SERVICES") == "1"


# ---------------------------------------------------------------------------
# Surface registry
#
# `surfaces` is the canonical per-surface reach map. Per-surface runner
# fixtures are generated by test medium:
#   playwright     -> <slug>_page    (Playwright page scoped to that surface)
#   subprocess-cli -> <slug>_runner  (invokes the binary, returns CompletedProcess)
# ---------------------------------------------------------------------------

_SURFACE_SPECS: dict[str, dict] = {
    # The built static export, served by the runner (`pnpm start:static` or
    # any static file server over services/site/out/).
    "site": {"medium": "playwright", "reach": "http://localhost:4173"},
    # The operator CLI, run from the repository root.
    "workbench": {"medium": "subprocess-cli", "reach": "node workbench/cli.mjs"},
}

_URL_MEDIUMS = {"playwright", "protocol-client"}


@pytest.fixture(scope="session")
def surfaces() -> dict[str, dict]:
    """Surface slug -> {"slug", "medium", "reach"} for every registered surface.

    reach is a base URL for playwright/protocol-client surfaces, a launch
    command for subprocess-cli surfaces, and None when the surface is not
    reachable yet (its runner fixture skips).
    """
    return {
        slug: {"slug": slug, "medium": spec["medium"], "reach": spec["reach"]}
        for slug, spec in _SURFACE_SPECS.items()
    }


@pytest.fixture(scope="session")
def cluster(surfaces):
    """Health-gate the served site: poll every URL-reach surface until it
    answers without a 5xx. FAIL if REQUIRE_SERVICES and anything is
    unreachable after the timeout; otherwise skip (local inner loop)."""

    @retry(stop=stop_after_delay(300), wait=wait_exponential(multiplier=1, min=1, max=8))
    def _wait():
        unreachable = []
        for spec in surfaces.values():
            if spec["medium"] in _URL_MEDIUMS and spec["reach"]:
                try:
                    r = httpx.get(spec["reach"], timeout=2.0)
                    if r.status_code >= 500:
                        unreachable.append(spec["reach"])
                except httpx.HTTPError:
                    unreachable.append(spec["reach"])
        if unreachable:
            raise RuntimeError(f"unreachable: {unreachable}")

    try:
        _wait()
    except (RetryError, RuntimeError) as exc:
        if REQUIRE_SERVICES:
            pytest.fail(f"site not healthy and STAYCURRENT_REQUIRE_SERVICES=1: {exc}")
        pytest.skip(f"site not reachable (build and serve services/site/out/ on :4173): {exc}")
    return surfaces


@pytest.fixture
def site_page(browser, surfaces):
    """Playwright page for the `site` surface. Relative page.goto()
    paths resolve against the surface's base URL."""
    base = surfaces["site"]["reach"]
    if base is None:
        pytest.skip("surface 'site' has no reachable base URL")
    context = browser.new_context(base_url=base)
    # A real Chrome auto-grants clipboard-write for a user-gesture-triggered
    # navigator.clipboard.writeText() (e.g. a code block's copy affordance)
    # without a permission prompt; Playwright's default context does not, so
    # grant it explicitly here rather than at every test that exercises a
    # copy-to-clipboard flow.
    context.grant_permissions(["clipboard-read", "clipboard-write"], origin=base)
    page = context.new_page()
    yield page
    context.close()


@pytest.fixture
def workbench_runner(surfaces):
    """Subprocess runner for the `workbench` CLI surface: run(args, ...) ->
    subprocess.CompletedProcess. Drive interactive (REPL) flows with pexpect
    against the same launch command."""
    command = surfaces["workbench"]["reach"]
    if command is None:
        pytest.skip("surface 'workbench' has no launch command registered")

    def run(args, input=None, timeout=30, env=None):
        cmd = [*shlex.split(command), *[str(a) for a in args]]
        return subprocess.run(
            cmd,
            input=input,
            capture_output=True,
            text=True,
            timeout=timeout,
            env={**os.environ, **(env or {})},
        )

    return run
